// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnsxwjmdsnqzvozjktyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuc3h3am1kc25xenZvemprdHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTY4NzUsImV4cCI6MjA2NjIzMjg3NX0.FBzyNrxRyTQvZZDjmrQ31YfcdIiuCtVHcCXdHfYqPJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);